// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/types';
import type * as prismicClient from '@prismicio/client';

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Home documents */
interface HomeDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismic.KeyTextField;
  /**
   * Hero Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_title
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  hero_title: prismic.KeyTextField;
  /**
   * Hero Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_description
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  hero_description: prismic.KeyTextField;
  /**
   * Hero Actions field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_actions[]
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  hero_actions: prismic.GroupField<Simplify<HomeDocumentDataHeroActionsItem>>;
  /**
   * Focus Areas field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.focus_areas[]
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  focus_areas: prismic.GroupField<Simplify<HomeDocumentDataFocusAreasItem>>;
  /**
   * Collaborators field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.collaborators[]
   * - **Tab**: Collaborators
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  collaborators: prismic.GroupField<
    Simplify<HomeDocumentDataCollaboratorsItem>
  >;
  /**
   * About Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_title
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  about_title: prismic.KeyTextField;
  /**
   * About Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_description
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  about_description: prismic.KeyTextField;
  /**
   * About Content field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_content
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  about_content: prismic.RichTextField;
  /**
   * About CTA Label field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_cta_label
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  about_cta_label: prismic.KeyTextField;
  /**
   * About CTA Link field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_cta_link
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  about_cta_link: prismic.LinkField;
  /**
   * About Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_image
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  about_image: prismic.ImageField<never>;
  /**
   * Projects Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.projects_title
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  projects_title: prismic.KeyTextField;
  /**
   * Projects Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.projects_description
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  projects_description: prismic.KeyTextField;
  /**
   * Projects CTA Label field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.projects_cta_label
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  projects_cta_label: prismic.KeyTextField;
  /**
   * Projects CTA Link field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.projects_cta_link
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  projects_cta_link: prismic.LinkField;
  /**
   * Projects field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.projects[]
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  projects: prismic.GroupField<Simplify<HomeDocumentDataProjectsItem>>;
  /**
   * Community Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.community_title
   * - **Tab**: Community
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  community_title: prismic.KeyTextField;
  /**
   * Community Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.community_description
   * - **Tab**: Community
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  community_description: prismic.KeyTextField;
  /**
   * Community GitHub Link field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.community_github_link
   * - **Tab**: Community
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  community_github_link: prismic.LinkField;
  /**
   * Community Outlinks field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.community_outlinks[]
   * - **Tab**: Community
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  community_outlinks: prismic.GroupField<
    Simplify<HomeDocumentDataCommunityOutlinksItem>
  >;
  /**
   * Callout Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.callout_title
   * - **Tab**: Callout
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  callout_title: prismic.KeyTextField;
  /**
   * Callout Caption field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.callout_caption
   * - **Tab**: Callout
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  callout_caption: prismic.KeyTextField;
  /**
   * Callout Description field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.callout_description
   * - **Tab**: Callout
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  callout_description: prismic.RichTextField;
  /**
   * Callout CTA Label field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.callout_cta_label
   * - **Tab**: Callout
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  callout_cta_label: prismic.KeyTextField;
  /**
   * Callout CTA Link field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.callout_cta_link
   * - **Tab**: Callout
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  callout_cta_link: prismic.LinkField;
  /**
   * Callout Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.callout_image
   * - **Tab**: Callout
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  callout_image: prismic.ImageField<never>;
  /**
   * Callout Active field in *Home*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home.callout_active
   * - **Tab**: Callout
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  callout_active: prismic.BooleanField;
}
/**
 * Item in Home → Hero Actions
 *
 */
export interface HomeDocumentDataHeroActionsItem {
  /**
   * Action Label field in *Home → Hero Actions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_actions[].action_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  action_label: prismic.KeyTextField;
  /**
   * Action Link field in *Home → Hero Actions*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_actions[].action_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  action_link: prismic.LinkField;
}
/**
 * Item in Home → Focus Areas
 *
 */
export interface HomeDocumentDataFocusAreasItem {
  /**
   * Focus Area field in *Home → Focus Areas*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.focus_areas[].focus_area
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  focus_area: prismic.KeyTextField;
}
/**
 * Item in Home → Collaborators
 *
 */
export interface HomeDocumentDataCollaboratorsItem {
  /**
   * Logo field in *Home → Collaborators*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.collaborators[].logo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismic.ImageField<never>;
}
/**
 * Item in Home → Projects
 *
 */
export interface HomeDocumentDataProjectsItem {
  /**
   * Project Title field in *Home → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.projects[].project_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  project_title: prismic.KeyTextField;
  /**
   * Project Description field in *Home → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.projects[].project_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  project_description: prismic.KeyTextField;
  /**
   * Project Link field in *Home → Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.projects[].project_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  project_link: prismic.LinkField;
  /**
   * Project Image field in *Home → Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.projects[].project_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  project_image: prismic.ImageField<never>;
}
/**
 * Item in Home → Community Outlinks
 *
 */
export interface HomeDocumentDataCommunityOutlinksItem {
  /**
   * Community Outlink Title field in *Home → Community Outlinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.community_outlinks[].community_outlink_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  community_outlink_title: prismic.KeyTextField;
  /**
   * Community Outlink Description field in *Home → Community Outlinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.community_outlinks[].community_outlink_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  community_outlink_description: prismic.KeyTextField;
  /**
   * Community Outlink CTA Label field in *Home → Community Outlinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.community_outlinks[].community_outlink_cta_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  community_outlink_cta_label: prismic.KeyTextField;
  /**
   * Community Outlink CTA Link field in *Home → Community Outlinks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.community_outlinks[].community_outlink_cta_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  community_outlink_cta_link: prismic.LinkField;
}
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, 'home', Lang>;
/** Content for Settings documents */
interface SettingsDocumentData {
  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}
/**
 * Item in Settings → Navigation
 *
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Navigation Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].navigation_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  navigation_label: prismic.KeyTextField;
  /**
   * Navigation Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].navigation_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  navigation_link: prismic.LinkField;
}
/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >;
export type AllDocumentTypes = HomeDocument | SettingsDocument;
declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      HomeDocumentData,
      HomeDocumentDataHeroActionsItem,
      HomeDocumentDataFocusAreasItem,
      HomeDocumentDataCollaboratorsItem,
      HomeDocumentDataProjectsItem,
      HomeDocumentDataCommunityOutlinksItem,
      HomeDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocument,
      AllDocumentTypes,
    };
  }
}
