// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home documents */
interface HomeDocumentData {
    /**
     * Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Hero Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.hero_title
     * - **Tab**: Hero
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    hero_title: prismicT.KeyTextField;
    /**
     * Hero Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.hero_description
     * - **Tab**: Hero
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    hero_description: prismicT.KeyTextField;
    /**
     * Hero Actions field in *Home*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: home.hero_actions[]
     * - **Tab**: Hero
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    hero_actions: prismicT.GroupField<Simplify<HomeDocumentDataHeroActionsItem>>;
    /**
     * Collaborators field in *Home*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: home.collaborators[]
     * - **Tab**: Collaborators
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    collaborators: prismicT.GroupField<Simplify<HomeDocumentDataCollaboratorsItem>>;
    /**
     * About Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_title
     * - **Tab**: About
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_title: prismicT.KeyTextField;
    /**
     * About Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_description
     * - **Tab**: About
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_description: prismicT.KeyTextField;
    /**
     * About Content field in *Home*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_content
     * - **Tab**: About
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about_content: prismicT.RichTextField;
    /**
     * About CTA Label field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_cta_label
     * - **Tab**: About
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_cta_label: prismicT.KeyTextField;
    /**
     * About CTA Link field in *Home*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_cta_link
     * - **Tab**: About
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    about_cta_link: prismicT.LinkField;
    /**
     * About Image field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_image
     * - **Tab**: About
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    about_image: prismicT.ImageField<never>;
    /**
     * About Outlinks field in *Home*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_outlinks[]
     * - **Tab**: About
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    about_outlinks: prismicT.GroupField<Simplify<HomeDocumentDataAboutOutlinksItem>>;
    /**
     * Projects Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.projects_title
     * - **Tab**: Projects
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    projects_title: prismicT.KeyTextField;
    /**
     * Projects Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.projects_description
     * - **Tab**: Projects
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    projects_description: prismicT.KeyTextField;
    /**
     * Projects CTA Label field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.projects_cta_label
     * - **Tab**: Projects
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    projects_cta_label: prismicT.KeyTextField;
    /**
     * Projects CTA Link field in *Home*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home.projects_cta_link
     * - **Tab**: Projects
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    projects_cta_link: prismicT.LinkField;
    /**
     * Projects field in *Home*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: home.projects[]
     * - **Tab**: Projects
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    projects: prismicT.GroupField<Simplify<HomeDocumentDataProjectsItem>>;
    /**
     * Community Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.community_title
     * - **Tab**: Community
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    community_title: prismicT.KeyTextField;
    /**
     * Community Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.community_description
     * - **Tab**: Community
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    community_description: prismicT.KeyTextField;
    /**
     * Community GitHub Link field in *Home*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home.community_github_link
     * - **Tab**: Community
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    community_github_link: prismicT.LinkField;
    /**
     * Community Outlinks field in *Home*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: home.community_outlinks[]
     * - **Tab**: Community
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    community_outlinks: prismicT.GroupField<Simplify<HomeDocumentDataCommunityOutlinksItem>>;
}
/**
 * Item in Home → Hero Actions
 *
 */
export interface HomeDocumentDataHeroActionsItem {
    /**
     * Action Label field in *Home → Hero Actions*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.hero_actions[].action_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    action_label: prismicT.KeyTextField;
    /**
     * Action Link field in *Home → Hero Actions*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home.hero_actions[].action_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    action_link: prismicT.LinkField;
}
/**
 * Item in Home → Collaborators
 *
 */
export interface HomeDocumentDataCollaboratorsItem {
    /**
     * Logo field in *Home → Collaborators*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.collaborators[].logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Item in Home → About Outlinks
 *
 */
export interface HomeDocumentDataAboutOutlinksItem {
    /**
     * About Outlink Title field in *Home → About Outlinks*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_outlinks[].about_outlink_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_outlink_title: prismicT.KeyTextField;
    /**
     * About Outlink Description field in *Home → About Outlinks*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_outlinks[].about_outlink_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_outlink_description: prismicT.KeyTextField;
    /**
     * About Outlink Label field in *Home → About Outlinks*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_outlinks[].about_outlink_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_outlink_label: prismicT.KeyTextField;
    /**
     * About Outlink Link field in *Home → About Outlinks*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home.about_outlinks[].about_outlink_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    about_outlink_link: prismicT.LinkField;
}
/**
 * Item in Home → Projects
 *
 */
export interface HomeDocumentDataProjectsItem {
    /**
     * Project Title field in *Home → Projects*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.projects[].project_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    project_title: prismicT.KeyTextField;
    /**
     * Project Description field in *Home → Projects*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.projects[].project_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    project_description: prismicT.KeyTextField;
    /**
     * Project Link field in *Home → Projects*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home.projects[].project_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    project_link: prismicT.LinkField;
    /**
     * Project Image field in *Home → Projects*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.projects[].project_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    project_image: prismicT.ImageField<never>;
}
/**
 * Item in Home → Community Outlinks
 *
 */
export interface HomeDocumentDataCommunityOutlinksItem {
    /**
     * Community Outlink Icon field in *Home → Community Outlinks*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.community_outlinks[].community_outlink_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    community_outlink_icon: prismicT.KeyTextField;
    /**
     * Community Outlink Title field in *Home → Community Outlinks*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.community_outlinks[].community_outlink_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    community_outlink_title: prismicT.KeyTextField;
    /**
     * Community Outlink Description field in *Home → Community Outlinks*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.community_outlinks[].community_outlink_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    community_outlink_description: prismicT.KeyTextField;
    /**
     * Community Outlink CTA Label field in *Home → Community Outlinks*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.community_outlinks[].community_outlink_cta_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    community_outlink_cta_label: prismicT.KeyTextField;
    /**
     * Community Outlink CTA Link field in *Home → Community Outlinks*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home.community_outlinks[].community_outlink_cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    community_outlink_cta_link: prismicT.LinkField;
}
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;
export type AllDocumentTypes = HomeDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomeDocumentData, HomeDocumentDataHeroActionsItem, HomeDocumentDataCollaboratorsItem, HomeDocumentDataAboutOutlinksItem, HomeDocumentDataProjectsItem, HomeDocumentDataCommunityOutlinksItem, HomeDocument, AllDocumentTypes };
    }
}
