name: 🚀 Feature Request For Open-Visualization Website
description: I have a suggestion (and may want to implement it)!
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        You have an idea how to improve the site? That's awesome!
        Before submitting, please have a look at the existing issues if there's already
        something related to your suggestion.
        We are also working on a relaunch at the moment, 
        so it might be a good idea to check out our plans there as well: https://github.com/openjs-foundation/open-visualization/issues.
  - type: textarea
    attributes:
      label: 'Enter your suggestions in details:'
      placeholder: |
        1. What I expected to happen.
        2. Your reason (if possible, images or videos are welcome).
        3. What I plan to do (Optional but better).
    validations:
      required: true
